# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-11-07 15:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangerate',
            name='rate',
            field=models.DecimalField(decimal_places=8, max_digits=19),
        ),
    ]
