# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-02 14:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangerate',
            name='rate',
            field=models.DecimalField(decimal_places=8, max_digits=20),
        ),
    ]
