# Generated by Django 2.2 on 2020-01-22 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0002_auto_20191107_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangerate',
            name='source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='rates', to='exchange.Currency'),
        ),
        migrations.AlterField(
            model_name='exchangerate',
            name='target',
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to='exchange.Currency'),
        ),
    ]
